kind: Pod
apiVersion: v1
metadata:
  name: node-selector
  labels:
    purpose: node-selector
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx