kind: Pod
apiVersion: v1
metadata:
  name: taint-tolerate
  labels:
    app: taint-tolerate-demo
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers: 
  - name: nginx
    image: nginx
  tolerations:
  - key: "Equal"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"