kind: Pod
apiVersion: v1
metadata:
  name: toleration
  labels:
    purpose: toleration
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
